# Generated by Django 4.2.6 on 2023-11-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returncom',
            name='ret',
        ),
        migrations.AddField(
            model_name='returncom',
            name='ret',
            field=models.ManyToManyField(to='app.com'),
        ),
    ]
