# Generated by Django 4.2.6 on 2023-11-01 10:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_returncom_ret_returncom_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returncom',
            name='ret',
            field=models.OneToOneField(on_delete=models.SET(app.models.Com), to='app.com'),
        ),
    ]
