# Generated by Django 4.2.6 on 2023-11-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_returncom_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returncom',
            name='ret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.com'),
        ),
    ]
