# Generated by Django 4.2.6 on 2023-11-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_returncom_ret_returncom_comname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='retOtheracc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard', models.CharField(max_length=50)),
                ('mouse', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='returnlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapname', models.CharField(max_length=50)),
                ('los', models.CharField(max_length=50)),
                ('lhdd', models.CharField(max_length=50)),
                ('lram', models.CharField(max_length=50)),
                ('lcm', models.CharField(max_length=50)),
                ('lsn', models.CharField(max_length=50)),
                ('prcl', models.CharField(max_length=50)),
                ('grcname', models.CharField(max_length=50)),
                ('gcs', models.CharField(max_length=50)),
                ('canv', models.CharField(max_length=50)),
            ],
        ),
    ]
