# Generated by Django 4.2.6 on 2023-11-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_retotheracc_returnlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='retotheracc',
            name='empname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returncom',
            name='empname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlap',
            name='empname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
