# Generated by Django 4.2.6 on 2023-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_retotheracc_empname_returncom_empname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empls', models.CharField(max_length=50)),
                ('otls', models.CharField(max_length=50)),
                ('gdt', models.DateField()),
                ('rdt', models.DateField()),
            ],
        ),
    ]
