# Generated by Django 4.2.6 on 2023-11-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reass',
            name='empls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enm', to='app.assest'),
        ),
        migrations.AlterField(
            model_name='retotheracc',
            name='empname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nme', to='app.assest'),
        ),
        migrations.AlterField(
            model_name='returncom',
            name='empname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='app.assest'),
        ),
        migrations.AlterField(
            model_name='returnlap',
            name='empname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='app.assest'),
        ),
    ]
