# Generated by Django 4.2.6 on 2023-11-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_reass_empls_alter_retotheracc_empname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assest',
            name='empls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epn', to='app.employee'),
        ),
    ]
