# Generated by Django 4.2.6 on 2023-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_assest_empls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assest',
            name='empls',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reass',
            name='empls',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retotheracc',
            name='empname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='returncom',
            name='empname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='returnlap',
            name='empname',
            field=models.CharField(max_length=50),
        ),
    ]
