# Generated by Django 4.2.6 on 2023-11-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_assest_empls_alter_reass_empls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assest',
            name='otls',
        ),
    ]
