# Generated by Django 4.2.23 on 2025-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='assest',
            name='usage_hours',
            field=models.IntegerField(default=0),
        ),
    ]
