# Generated by Django 4.2.23 on 2025-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_assest_usage_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='assest',
            name='accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assest',
            name='last_depreciation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assest',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assest',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assest',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assest',
            name='useful_life_years',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
